### ISSUE TITLE
color palette 

### ISSUE THREAD

**Issue by venatiodecorus** [mikedesu/asciishade#6]
changing colors one by one is quite tedious. it would be nice to have a quicker way to select colors.

**Comment by mikedesu** [comment]
Yes. I agree. Foreground/background color cycling is coming in a new release. I am limiting colors early in development because while you can have 256 colors for foreground or background, curses allows you to define up to 32768 color pairs, so I plan on having a default palette as well as allowing the user to define, import, and export their own palette. 

c, C, V, and v are still planned to be the characters used to cycle foreground and background colors. Closing for now.
